Initial commit: added .github/workflows/linters.yml
valentino2105/Hello-Microverse pull request #2
Opened 2023-05-30 15:38 UTC by valentino2105

2023-05-31 13:28 UTC, NatiG25 requested changes
## :yellow_circle: CHANGES REQUIRED :yellow_circle: 

## Hi @valentino2105 :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Added test.md file to .gitignore.
:heavy_check_mark: Created two an index.html & style.css files.

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._
:x: Please, have a proper branch name. This might seem like a minor thing but our goal is to make this a habit because when building more complex projects having a proper branch name helps in reducing complexity when adding changes.

:x: Kindly, make sure to not close any PR until it has been approved. This can be a reason for invalidation but since you're new to the program I didn't invalidate it.

:x: I recommend following the GitHub flow, where you'd have only one commit on the `main` branch then adding all changes into the `feature` branch. Then merging the `feature` branch with the `main` branch once the project has been approved. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please consider:
- Great job! On adding meaningful commits but I suggest making it imperative. For example, instead of 'Added test.md to gitignore' use 'Add test.md to gitignore'.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 13:28 UTC, NatiG25 commented on README.md
> +>>>>>>> dfb9c70ebbc9081e1a01c61190c97ac81e63fa8b
- [ ] Great job! :rocket: On adding the LICENSE file but I recommend removing unnecessary lines from your README. This will make your README more readable.

2023-05-31 14:18 UTC, valentino2105 commented on README.md
> +>>>>>>> dfb9c70ebbc9081e1a01c61190c97ac81e63fa8b
Thank you @NatiG25! I renamed the branch locally and in the repository and removed the unnecessary files from README file. 
Also, thank you for understanding and not punishing me for closing the pull request.

2023-05-31 14:25 UTC, valentino2105 commented on README.md
> +>>>>>>> dfb9c70ebbc9081e1a01c61190c97ac81e63fa8b
@NatiG25 should I also delete the branch feature-1 after I renamed it to feature/added-Hello-Microverse?

2023-06-01 05:25 UTC, shella12 approved these changes
Hi @valentino2105, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Implemented all requirements 👏 

## Optional suggestions

- [ ] [OPTIONAL]  I suggest using a more descriptive name for your feature branch instead of `feature-1`. Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section’) 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 05:25 UTC, shella12 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] [OPTIONAL] I would suggest you to remove `Live Demo` section from your README since this project does not require you to deploy your site. `Live Demo ` is only required for projects that are deployed.

2023-06-01 05:33 UTC, merged